#!/bin/bash


if tmux list-sessions &>/dev/null; then
	TMUX_RUNNING=0
else
	TMUX_RUNNING=1
fi

get_sessions_by_mru() {
	tmux list-sessions -F '#{session_last_attached} #{session_name}' | sort --numeric-sort --reverse | awk '{print $2}'
}

get_zoxide_results() {
	zoxide query -l | sed -e "$HOME_REPLACER"
}

get_fzf_results() {
	if [ "$TMUX_RUNNING" -eq 0 ]; then
		fzf_default_results="$(tmux show -gqv '@t-fzf-default-results')"
		case $fzf_default_results in
		sessions)
			get_sessions_by_mru
			;;
		zoxide)
			get_zoxide_results
			;;
		*)
			get_sessions_by_mru && get_zoxide_results # default shows both
			;;
		esac
	else
		get_zoxide_results # only show zoxide results when outside tmux
	fi
}

get_fzf_results
