#!/usr/bin/env bash
# Took from https://github.com/joshmedeski/t-smart-tmux-session-manager
# Wasn't working so changed it then added some features I want

FZF_TMUX_OPTS="-p 53%,58% \
--color=bg+:#303446,bg:#303446,spinner:#f2d5cf,hl:#e78284,gutter:-1 \
--color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf \
--color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6"

# determine if the tmux server is running
if tmux list-sessions &>/dev/null; then
	TMUX_RUNNING=0
else
	TMUX_RUNNING=1
fi

# determine the user's current position relative tmux:
# serverless - there is no running tmux server
# attached   - the user is currently attached to the running tmux server
# detached   - the user is currently not attached to the running tmux server
T_RUNTYPE="serverless"
if [ "$TMUX_RUNNING" -eq 0 ]; then
	if [ "$TMUX" ]; then # inside tmux
		T_RUNTYPE="attached"
	else # outside tmux
		T_RUNTYPE="detached"
	fi
fi

# display help text with an argument
if [ "$1" = "-h" ] || [ "$1" == "--help" ]; then
	printf "\n"
	printf "\033[1m  t - the smart tmux session manager\033[0m\n"
	printf "\033[37m  https://github.com/joshmedeski/t-smart-tmux-session-manager\n"
	printf "\n"
	printf "\033[32m  Run interactive mode\n"
	printf "\033[34m      t\n"
	printf "\033[34m        ctrl-s list only tmux sessions\n"
	printf "\033[34m        ctrl-x list only zoxide results\n"
	printf "\033[34m        ctrl-f list results from the find command\n"
	printf "\n"
	printf "\033[32m  Go to session (matches tmux session, zoxide result, or directory)\n"
	printf "\033[34m      t {name}\n"
	printf "\n"
	printf "\033[32m  Open popup (while in tmux)\n"

	if [ "$TMUX_RUNNING" -eq 0 ]; then
		T_BIND=$(tmux show-option -gvq "@t-bind")
		if [ "$T_BIND" = "" ]; then
			T_BIND="T"
		fi
		printf "\033[34m      <prefix>+%s\n" "$T_BIND"
		printf "\033[34m        ctrl-s list only tmux sessions\n"
		printf "\033[34m        ctrl-x list only zoxide results\n"
		printf "\033[34m        ctrl-f list results from the find command\n"
	else
		printf "\033[34m      start tmux server to see bindings\n" "$T_BIND"
	fi

	printf "\n"
	printf "\033[32m  Show help\n"
	printf "\033[34m      t -h\n"
	printf "\033[34m      t --help\n"
	printf "\n"
	exit 0
fi

HOME_REPLACER=""                                          # default to a noop
echo "$HOME" | grep -E "^[a-zA-Z0-9\-_/.@]+$" &>/dev/null # chars safe to use in sed
HOME_SED_SAFE=$?
if [ $HOME_SED_SAFE -eq 0 ]; then # $HOME should be safe to use in sed
	HOME_REPLACER="s|^$HOME/|~/|"
fi

get_fzf_prompt() {
	local fzf_prompt
	local fzf_default_prompt='>  '
	if [ "$TMUX_RUNNING" -eq 0 ]; then
		fzf_prompt="$(tmux show -gqv '@t-fzf-prompt')"
	fi
	[ -n "$fzf_prompt" ] && echo "$fzf_prompt" || echo "$fzf_default_prompt"
}
PROMPT=$(get_fzf_prompt)

get_fzf_find_binding() {
	local fzf_find_binding
	local fzf_find_binding_default='ctrl-f:change-prompt(find> )+reload(find ~ -maxdepth 3 -type d)'
	if [ "$TMUX_RUNNING" -eq 0 ]; then
		fzf_find_binding="$(tmux show -gqv '@t-fzf-find-binding')"
	fi
	[ -n "$fzf_find_binding" ] && echo "$fzf_find_binding" || echo "$fzf_find_binding_default"
}

FIND_BIND=$(get_fzf_find_binding)

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

RELOAD_COMMAND="source $CURRENT_DIR/session-manager-list-generator"

get_fzf_results() {
    eval $RELOAD_COMMAND
}

fzf_border_label_default=' t - smart tmux session manager '
BORDER_LABEL="Choose session"

HEADER=" ^s sessions ^x zoxide ^f find ⎇ bs delete session ^d new session"
SESSION_BIND="ctrl-s:change-prompt(sessions> )+reload(tmux list-sessions -F '#S')"
ZOXIDE_BIND="ctrl-x:change-prompt(zoxide> )+reload(zoxide query -l | sed -e \"$HOME_REPLACER\")"
DELETE_BIND="alt-bs:execute(~/.config/tmux/tmux-sessionist/scripts/kill_session.sh '{}')+reload($RELOAD_COMMAND)"
NEW_SESSION_BIND="ctrl-d:become(~/.config/tmux/tmux-sessionist/scripts/new_session.sh '{q}')"

TAB_BIND="tab:down,btab:up"

if [ $# -eq 1 ]; then # argument provided
	zoxide query "$1" &>/dev/null
	ZOXIDE_RESULT_EXIT_CODE=$?
	if [ $ZOXIDE_RESULT_EXIT_CODE -eq 0 ]; then # zoxide result found
		RESULT=$(zoxide query "$1")
	else # no zoxide result found
		ls "$1" &>/dev/null
		LS_EXIT_CODE=$?
		if [ $LS_EXIT_CODE -eq 0 ]; then # directory found
			RESULT=$1
		else # no directory found
			echo "No directory found."
			exit 1
		fi
	fi
else # argument not provided
	case $T_RUNTYPE in
	attached)
		if [[ -z ${FZF_TMUX_OPTS} ]]; then
			FZF_TMUX_OPTS="-p 53%,58% \
--color=bg+:#303446,bg:#303446,spinner:#f2d5cf,hl:#e78284,gutter:-1 \
--color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf \
--color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6"
		fi

		RESULT=$(
			(get_fzf_results) | fzf-tmux \
				--bind "$FIND_BIND" \
				--bind "$SESSION_BIND" \
				--bind "$TAB_BIND" \
				--bind "$ZOXIDE_BIND" \
                --bind "$DELETE_BIND" \
                --bind "$NEW_SESSION_BIND" \
				--header "$HEADER" \
				--no-sort \
				--prompt "$PROMPT" \
                --print-query \
				$FZF_TMUX_OPTS
                            # --border-label "$BORDER_LABEL" \
		)
		;;
	detached)
		RESULT=$(
			(get_fzf_results) | fzf \
				--bind "$FIND_BIND" \
				--bind "$SESSION_BIND" \
				--bind "$TAB_BIND" \
				--bind "$ZOXIDE_BIND" \
                --bind "$DELETE_BIND" \
				--border \
				--header "$HEADER" \
				--no-sort \
				--prompt "$PROMPT" \
                --print-query
                            # --border-label "$BORDER_LABEL" \
		)
		;;
	serverless)
		RESULT=$(
			(get_fzf_results) | fzf \
				--bind "$FIND_BIND" \
				--bind "$TAB_BIND" \
				--bind "$ZOXIDE_BIND" \
                --bind "$DELETE_BIND" \
				--border \
				--header " ^x zoxide ^f find" \
				--no-sort \
				--prompt "$PROMPT" \
                --print-query
                            # --border-label "$BORDER_LABEL" \
		)
		;;
	esac
fi


q=$(echo -e "$RESULT" | sed -n '1 p')
RESULT=$(echo -e "$RESULT" | sed -n '2 p')

if [ "$RESULT" = "" ]; then
    source ~/.config/tmux/tmux-sessionist/scripts/new_session.sh $q
    exit
fi

if [ $HOME_SED_SAFE -eq 0 ]; then
	RESULT=$(echo "$RESULT" | sed -e "s|^~/|$HOME/|") # get real home path back
fi

zoxide add "$RESULT" &>/dev/null # add to zoxide database

if [[ $RESULT != /* ]]; then # not folder path from zoxide result
	SESSION_NAME=$RESULT
elif [[ $T_SESSION_USE_GIT_ROOT == 'true' ]]; then
	GIT_ROOT=$(git -C $RESULT rev-parse --show-toplevel 2>/dev/null) && echo $GIT_ROOT >/dev/null
	if [[ $? -ne 0 ]]; then # not inside git repository
		SESSION_NAME=$(basename "$RESULT" | tr ' .:' '_')
	else # is in git repository
		BASENAME=$(basename $GIT_ROOT)
		RELATIVE_PATH=${RESULT#$GIT_ROOT}
		SEPARATOR="/"
		FORMATTED_PATH="${RELATIVE_PATH//\//$SEPARATOR}"
		SESSION_NAME=$(echo $BASENAME$FORMATTED_PATH | tr ' .:' '_')
	fi
elif [[ $T_SESSION_NAME_INCLUDE_PARENT == 'true' ]]; then
	SESSION_NAME=$(echo "$RESULT" | tr ' .:' '_' | awk -F "/" '{print $(NF-1)"/"$NF}')
else
	SESSION_NAME=$(basename "$RESULT" | tr ' .:' '_')
fi

if [ "$T_RUNTYPE" != "serverless" ]; then
	SESSION=$(tmux list-sessions -F '#S' | grep "^$SESSION_NAME$") # find existing session
fi

if [ "$SESSION" = "" ]; then # session is missing
	SESSION="$SESSION_NAME"
	if [ -e $RESULT/.t ]; then
		tmux new-session -d -s "$SESSION" -c "$RESULT" $RESULT/.t # create session and run .t startup script
	else
		tmux new-session -d -s "$SESSION" -c "$RESULT" # create session
	fi
fi

case $T_RUNTYPE in # attach to session
attached)
	tmux switch-client -t "$SESSION"
	;;
detached | serverless)
	tmux attach -t "$SESSION"
	;;
esac
