#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# make a tmp dir for all the stuff we need
mkdir /tmp/sketchybar
# if it already exists delete all files (commands assume empty tmp dir)
rm /tmp/sketchybar/*

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

bar=(
  height=28
  blur_radius=100
  position=top
  sticky=off
  padding_left=10
  padding_right=10
  color=$BAR_COLOR
)

defaults=(
        icon.font="JetBrainsMono NF:Regular:12.0"
        icon.color="$ITEM_FG"
        icon.highlight_color="$ITEM_ACCENT"
        label.font="SF Pro:Semibold:10.0" 
        label.color="$ITEM_FG"
        label.highlight_color="$ITEM_ACCENT"
        background.color=$BAR_COLOR
        background.corner_radius=5            
        background.height=22                  
        padding_left=2                        
        padding_right=2                       
        label.padding_left=2                  
        label.padding_right=10                
        icon.padding_left=5                  
        icon.padding_right=4
    )
sketchybar --bar "${bar[@]}" --default "${defaults[@]}" --hotload true

# -- Left Side Items --
source $ITEM_DIR/aerospace.sh
# source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.
sketchybar --update
